# Generated by Django 5.2.8 on 2025-11-24 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Enter contribution name (e.g. Kgotla Monthly Fee or Kgotla Funeral Fund)', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('event', 'Event / Celebration'), ('burial', 'Burial / Funeral Fund'), ('savings', 'Savings / Stokvel'), ('investment', 'Investment Fund'), ('business', 'Business or Income Project'), ('holiday', 'Holiday / Travel Fund'), ('grocery', 'Grocery / Monthly Food Club'), ('emergency', 'Emergency Support'), ('education', 'Education or Skills Fund'), ('other', 'Other')], default='other', help_text='Select the contribution category (e.g. Burial, Savings, Event)', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Default amount to be contributed for this type', max_digits=10)),
                ('recurrence', models.CharField(choices=[('once_off', 'Once Off'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='once_off', help_text='Specify if this contribution is once-off, monthly, or annual', max_length=20)),
                ('scope', models.CharField(choices=[('clan', 'Entire Kgotla'), ('family_leaders', 'Family Leaders'), ('family', 'Specific Family'), ('executives', 'Executives')], default='clan', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='For Annual and Once-off contributions', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contributions', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_contribution_types', to='accounts.family')),
            ],
            options={
                'verbose_name': 'Contribution Type',
                'verbose_name_plural': 'Contribution Types',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MemberContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Receipt or transaction reference', max_length=100, null=True, unique=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('NOT_PAID', 'Not paid'), ('CANCELLED', 'Cancelled'), ('PARTIALLY_PAID', 'PARTIALLY PAID')], db_index=True, default='NOT_PAID', max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_contributions', to=settings.AUTH_USER_MODEL)),
                ('contribution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_contributions', to='contributions.contributiontype')),
            ],
            options={
                'verbose_name': 'Member Contribution',
                'verbose_name_plural': 'Member Contributions',
                'ordering': ['-created'],
                'unique_together': {('account', 'contribution_type', 'due_date')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_method_type', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method_card_holder', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method_masked_card', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method_scheme', models.CharField(blank=True, max_length=50, null=True)),
                ('checkout_id', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Deposit'), ('mobile', 'Yoco Mobile Payment'), ('other', 'Other')], default='cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Receipt or transaction reference', max_length=100, null=True)),
                ('receipt', models.CharField(blank=True, help_text='Receipt number from bank/payment provider', max_length=100, null=True)),
                ('proof_of_payment', models.FileField(blank=True, help_text='Upload bank statement, screenshot, or receipt image', null=True, upload_to='payments/proof/')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('is_approved', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Payment verification status', max_length=20)),
                ('payment_verified_date', models.DateTimeField(blank=True, help_text='When payment was verified', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason if payment was rejected', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('contribution_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contributions.contributiontype')),
                ('member_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contributions.membercontribution')),
                ('payment_verified_by', models.ForeignKey(blank=True, help_text='Admin/treasurer who verified/approved payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(help_text='Treasurer or admin who logged this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['account', '-payment_date'], name='contributio_account_0c4a85_idx'), models.Index(fields=['is_approved', 'payment_date'], name='contributio_is_appr_e87728_idx')],
            },
        ),
    ]
