# Generated by Django 5.2.8 on 2025-12-06 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_clandocument_options'),
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='contribution_type',
        ),
        migrations.AlterField(
            model_name='contributiontype',
            name='family',
            field=models.ForeignKey(blank=True, help_text='Select family if this contribution is only for specific family', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_contribution_types', to='accounts.family'),
        ),
        migrations.AlterField(
            model_name='contributiontype',
            name='scope',
            field=models.CharField(choices=[('clan', 'Entire Kgotla'), ('family_leaders', 'Family Leaders'), ('family', 'Specific Family'), ('executives', 'Executives')], default='clan', help_text='Specify if this contribution is Entire Kgotla, Family leader only, or specific family', max_length=20),
        ),
        migrations.AlterField(
            model_name='membercontribution',
            name='is_paid',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('AWAITING APPROVAL', 'Awaiting Approval'), ('NOT_PAID', 'Not paid'), ('CANCELLED', 'Cancelled'), ('PARTIALLY_PAID', 'PARTIALLY PAID')], db_index=True, default='NOT_PAID', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_approved',
            field=models.CharField(choices=[('NOT PAID', 'Not paid'), ('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Payment verification status', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='member_contribution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='contributions.membercontribution'),
        ),
    ]
