# Generated by Django 5.2.8 on 2025-11-20 21:53

import accounts.utils.file_handlers
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import utilities.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, help_text='Enter cellphone number', max_length=15, null=True, validators=[utilities.validators.validate_rsa_phone])),
                ('profile_image', models.ImageField(blank=True, help_text='Upload profile image', null=True, upload_to=accounts.utils.file_handlers.handle_profile_upload)),
                ('title', models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('DR', 'Dr'), ('PROF', 'Prof.')], max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=30)),
                ('maiden_name', models.CharField(blank=True, help_text='Enter your maiden name', max_length=300, null=True)),
                ('biography', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('KGOSANA', 'Kgosana'), ('CLAN_CHAIRPERSON', 'Chairperson'), ('MEMBER', 'Member'), ('DEP_CHAIRPERSON', 'Deputy Chairperson'), ('SECRETARY', 'Secretary'), ('DEP_SECRETARY', 'Deputy Secretary'), ('TREASURER', 'Treasurer')], default='MEMBER', max_length=100)),
                ('is_approved', models.BooleanField(default=False, help_text='Should be approved by executives')),
                ('is_family_leader', models.BooleanField(default=False, help_text='Tick if member is a family leader')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Enter family name e.g Dladla Family', max_length=300, unique=True)),
                ('slug', models.SlugField(max_length=400, unique=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Should be approved by executives')),
                ('leader', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_leader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.family'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['is_approved'], name='accounts_fa_is_appr_f5e68a_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['slug'], name='accounts_fa_slug_8bd0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_approved'], name='accounts_ac_is_appr_dd123d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['family'], name='accounts_ac_family__c4b227_idx'),
        ),
    ]
