# Generated by Django 5.2.8 on 2025-12-06 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Enter the document title', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('minutes', 'Meeting Minutes'), ('report', 'Financial / Contribution Report'), ('event', 'Event Notice or Program'), ('policy', 'Policy / Constitution'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to='clan_documents/%Y/%m/')),
                ('visibility', models.CharField(choices=[('clan', 'Entire Clan'), ('family', 'Specific Family'), ('private', 'Private (Admin Only)')], default='clan', help_text='Who can access this document', max_length=20)),
                ('family', models.ForeignKey(blank=True, help_text='Optional: restrict this document to a specific family', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.family')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clan Document',
                'verbose_name_plural': 'Clan Documents',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Enter meeting title', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meeting_type', models.CharField(choices=[('online', 'Online Meeting'), ('in_person', 'Live / In-Person Meeting')], default='in_person', help_text='Specify whether this meeting is online or in-person.', max_length=20)),
                ('meeting_venue', models.CharField(blank=True, help_text='Meeting Venue for in-person meetings', max_length=150, null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Link for online meetings (e.g., Zoom, Google Meet).', null=True)),
                ('audience', models.CharField(choices=[('clan', 'Entire Kgotla'), ('family_leaders', 'Family Leaders'), ('family', 'Specific Family'), ('executives', 'Executives')], default='clan', help_text='Specify who this meeting is for.', max_length=30)),
                ('meeting_date', models.DateTimeField(help_text='Start date and time of the meeting')),
                ('meeting_end_date', models.DateTimeField(help_text='End date and time of the meeting')),
                ('created_by', models.ForeignKey(help_text='User who created this meeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_created', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, help_text='Optional: assign this meeting to a specific family if needed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='accounts.family')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-meeting_date'],
            },
        ),
    ]
