# Generated by Django 5.2.8 on 2025-12-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clandocument_meeting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clandocument',
            options={'ordering': ['-created'], 'verbose_name': 'Kgotla Document', 'verbose_name_plural': 'Kgotla Documents'},
        ),
    ]
