# Generated by Django 5.2.8 on 2025-12-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_clandocument_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Enter your date of birth', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='langueges_spoken',
            field=models.CharField(blank=True, help_text='Enter languages you speak, separated by commas', max_length=300, null=True),
        ),
    ]
