# Generated by Django 5.2.8 on 2026-01-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_birth_date_account_langueges_spoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, help_text='Enter your ID number', max_length=15, null=True, unique=True),
        ),
    ]
