# Generated by Django 5.2.8 on 2026-01-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self-Employed'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired'), ('STUDENT', 'Student'), ('HOMEMAKER', 'Homemaker'), ('DISABLED', 'Disabled')], help_text='Select employment status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='member_classification',
            field=models.CharField(blank=True, choices=[('RELATIVE', 'Relative'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('GRANDPARENT', 'Grandparent'), ('OTHER', 'Other')], help_text='Select member classification', max_length=20, null=True),
        ),
    ]
