# Generated by Django 5.2.8 on 2026-02-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_employment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Status of the meeting (e.g., Scheduled, In Progress, Completed).', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='member_classification',
            field=models.CharField(blank=True, choices=[('RELATIVE', 'Relative'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('GRANDPARENT', 'Grandparent'), ('GRANDCHILD', 'Grandchild'), ('GRANDPARENT_IN_LAW', 'Grandparent-in-law'), ('SIBLING', 'Sibling'), ('PARENT_IN_LAW', 'Parent-in-law'), ('OTHER', 'Other')], help_text='Select member classification', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('KGOSANA', 'Kgosana'), ('MMAKGOSANA', 'Mmakgosana'), ('CLAN_CHAIRPERSON', 'Chairperson'), ('MEMBER', 'Member'), ('DEP_CHAIRPERSON', 'Deputy Chairperson'), ('SECRETARY', 'Secretary'), ('DEP_SECRETARY', 'Deputy Secretary'), ('TREASURER', 'Treasurer')], default='MEMBER', max_length=100),
        ),
    ]
