# Generated by Django 5.2.8 on 2026-02-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_meeting_meeting_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('KGOSANA', 'Kgosana'), ('MMAKGOSANA', 'Mmakgosana'), ('CLAN_CHAIRPERSON', 'Chairperson'), ('MEMBER', 'Member'), ('DEP_CHAIRPERSON', 'Deputy Chairperson'), ('SECRETARY', 'Secretary'), ('DEP_SECRETARY', 'Deputy Secretary'), ('TREASURER', 'Treasurer'), ('SPONSOR', 'Sponser')], default='MEMBER', max_length=100),
        ),
    ]
