# Generated by Django 5.2.8 on 2026-04-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='family',
        ),
        migrations.DeleteModel(
            name='ClanDocument',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
