# Generated by Django 5.2.8 on 2026-04-20 12:02

import accounts.utils.file_handlers
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakgomong_kgotla_yamalla', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kgotlabalance',
            name='total_costs',
        ),
        migrations.AlterField(
            model_name='kgotlabalance',
            name='slug',
            field=models.SlugField(default='general-fund-balance', max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='kgotlabalance',
            name='title',
            field=models.CharField(default='General Fund Balance', help_text='Enter balance title e.g General Fund Balance', max_length=300, unique=True),
        ),
        migrations.CreateModel(
            name='KgotlaExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Enter expense title e.g "Catering for Annual Meeting"', max_length=300)),
                ('slug', models.SlugField(max_length=400, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter expense amount', max_digits=12)),
                ('description', models.TextField(blank=True, help_text='Enter a description for this expense', null=True)),
                ('incurred_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the expense was incurred')),
                ('proof_of_expense', models.FileField(blank=True, help_text='Upload proof of expense (e.g., receipt, invoice)', null=True, upload_to=accounts.utils.file_handlers.handle_profile_upload)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kgotla Expense',
                'verbose_name_plural': 'Kgotla Expenses',
                'ordering': ['-incurred_date'],
            },
        ),
    ]
