# Generated by Django 5.2.8 on 2026-04-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakgomong_kgotla_yamalla', '0002_remove_kgotlabalance_total_costs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgotlaexpense',
            name='approved',
            field=models.BooleanField(default=False, help_text='Indicates whether this expense has been approved by the clan chairperson or secretary'),
        ),
    ]
