# Generated by Django 5.2.8 on 2026-04-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakgomong_kgotla_yamalla', '0003_kgotlaexpense_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgotlaexpense',
            name='recurring',
            field=models.CharField(choices=[('once_off', 'Once Off'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='once_off', help_text='Indicates whether this is a recurring expense', max_length=10),
        ),
    ]
