# Generated by Django 5.2.8 on 2026-07-07 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakgomong_kgotla_yamalla', '0004_kgotlaexpense_recurring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kgotlabalance',
            options={'ordering': ['-updated'], 'verbose_name': 'Update Kgotla Balance', 'verbose_name_plural': 'Update Kgotla Balance'},
        ),
    ]
